sequenceDiagram
    participant CS as Charging Station (OCTT)
    participant CSMS as CSMS (System Under Test)

    Note over CS,CSMS: Test Case: TC_B_10_CSMS
    Note over CS,CSMS: Set Variables - multiple values

    Note over CSMS: Manual Action: Request CSMS to set data for<br/>OCPPCommCtrlr.OfflineThreshold<br/>AuthCtrlr.AuthorizeRemoteStart

    CSMS->>CS: 1. SetVariablesRequest
    Note left of CSMS: setVariableData[1]:<br/>variable.name = "OfflineThreshold"<br/>component.name = "OCPPCommCtrlr"<br/>attributeValue = "123"<br/>setVariableData[2]:<br/>variable.name = "AuthorizeRemoteStart"<br/>component.name = "AuthCtrlr"<br/>attributeValue = "false"

    CS-->>CSMS: 2. SetVariablesResponse
