sequenceDiagram
    participant EV as EV Driver
    participant CS as Charging Station
    participant CSMS
    participant PS as Payment System
    
    EV->>CS: Plugs in Charging Cable
    CS->>CSMS: StatusNotificationRequest(Occupied)
    CSMS->>CS: StatusNotificationResponse()
    CS->>CSMS: TransactionEventRequest(eventType=Started, transactionId=AB1234, timestamp, evse.id=1, evse.connectorId=1, meterValues)
    CSMS->>CS: TransactionEventResponse(...)
    
    EV->>CS: Uses credit/debit card
    CS->>PS: Financial transaction
    PS->>CSMS: authorized(TransactionReference=1234, CS=CS-001, EVSE=1)
    
    Note over CSMS: generate unique id()<br>result = 4444
    
    CSMS->>CS: RequestStartTransactionRequest(evseId=1, idToken(id=4444, type=Central))
    CS->>CSMS: RequestStartTransactionResponse(Accepted)
    
    Note over CS: lock connector (if cable not permanently attached)
    Note over CS: Start energy offer
    
    CS->>CSMS: TransactionEventRequest(eventType=Updated, transactionId=AB1234, seqNo=1, timestamp, chargingState=Charging, trigger=Authorized, idToken(id=4444, type=Central))
    CSMS->>CS: TransactionEventResponse(idTokenInfo.status=Accepted)
