sequenceDiagram
    participant EV as EV Driver App
    participant CSMS
    participant CS as Charging Station
    Note over CS: Cable is plugged in
    EV->>CSMS: Start Charging (CS-001)
    Note over CSMS: determine unique id()
    Note over CSMS: result = 4444
    CSMS->>CS: RequestStartTransactionRequest(evseId = 1, idToken(id = 4444, type = Central))
    CS->>CSMS: RequestStartTransactionResponse(Accepted)
    Note over CS: Transaction starts
    CS->>CSMS: TransactionEventRequest(eventType = Updated, transactionId = AB1234, evse.id = 1, evse.connectorId = 1, meterValues, timestamp)
    CSMS->>CS: TransactionEventResponse(...)
    Note over CS: Transaction ongoing on Charging Station
