sequenceDiagram
    participant Driver as EV Driver
    participant Station as Charging Station
    participant CSMS
    participant Terminal as Payment Terminal
    
    Note over Driver, Terminal: Initial Charging Process
    
    Driver->>Station: Plug in charging cable
    Station->>CSMS: StatusNotificationRequest(Occupied)
    CSMS->>Station: StatusNotificationResponse()
    Station->>CSMS: TransactionEventRequest(eventType = Started, ...)
    CSMS->>Station: TransactionEventResponse(...)
    
    Driver->>Station: Present parking ticket (1234)
    Station->>CSMS: AuthorizeRequest(idToken(id = 1234, type = Local))
    CSMS->>Station: AuthorizeResponse(...)
    
    opt Notification
        Note over Station: Start Charging
    end
    
    Station->>CSMS: TransactionEventRequest(eventType = Updated, transactionId = AB1234, chargingState = Charging, trigger = Authorized, idToken.id = 1234, meterValues, ...)
    CSMS->>Station: TransactionEventResponse(idTokenInfo.status = Accepted, ...)
    
    Note over Driver, Terminal: Later - Payment and Completion
    
    Driver->>Terminal: Present parking ticket (1234)
    Terminal->>Terminal: Match ticketId with TransactionId()
    Terminal->>CSMS: RequestStopTransactionRequest(transactionId = AB1234)
    CSMS->>Terminal: RequestStopTransactionResponse(Accepted)
    
    CSMS->>Station: TransactionEventRequest(eventType = Updated, transactionId = AB1234, chargingState = EVConnected, trigger = RemoteStop, idToken.id = 1234, meterValues, ...)
    Station->>CSMS: TransactionEventResponse(...)
    
    Driver->>Terminal: Get cost(id = 1234)
    Driver->>Terminal: Pay for parking and charging
    
    opt Notification
        Note over Driver: Unplug cable
    end
    
    Station->>CSMS: StatusNotificationRequest(Available)
    CSMS->>Station: StatusNotificationResponse()
    Station->>CSMS: TransactionEventRequest(eventType = Ended, transactionId = AB1234, meterValues, ...)
    CSMS->>Station: TransactionEventResponse(...)
