sequenceDiagram
    actor EV as EV Driver
    participant CS as Charging Station
    participant CSMS as CSMS
    
    EV->>CS: Present IdToken
    Note over CS: check local authorization list()
    Note over CS: [cached tariff: 0.23/kWh]
    
    alt IdToken not known or IdToken status not Accepted
        CS->>CSMS: AuthorizeRequest(IdToken)
        CSMS->>CS: AuthorizeResponse(Accepted)
    end
    
    opt notification
        Note over CS: [tariff: 0.23/kWh]
    end
    
    CS->>CS: lock connector
    CS->>EV: start energy offer
    
    Note over CS,CSMS: Requirements:
    Note over CS,CSMS: C14.FR.01: Local Auth List entries have priority over Auth Cache
    Note over CS,CSMS: C14.FR.02: If IdToken in Local Auth List with status Accepted, start without AuthorizeRequest
    Note over CS,CSMS: C14.FR.03: If IdToken in list with status OTHER than Accepted, send AuthorizeRequest
    Note over CS,CSMS: C14.FR.04: If IdToken has valid cacheExpiryDateTime, start without AuthorizeRequest
    Note over CS,CSMS: C14.FR.05: If IdToken has expired cacheExpiryDateTime, send AuthorizeRequest
